Restaurant/config/routes.rb
Restaurant::Application.routes.draw do
  get "admin/new_menu"
  
  get "admin/view"

  get "contact/contact"

  get "menu/displayMenu"
  
  resources :bookings

  resources :subscribes
  
  get "menu/new"

  get "index/index"
  
  get "admin/edit_menu"
  
  get "menu/edit"

  match '/menu' => 'menu#displayMenu'
  match '/index' => 'index#index'
  match '/contact' => 'contact#contact'
  match '/admin' => 'admin#view'
  match '/admins/new' => 'admin#new_menu'
  match '/admins' => 'admin#create_menu'
  match '/menus' => 'menu#create'
  match '/menus/edit/:id' => 'menu#edit'

  root :to => 'index#index'

  match ':controller(/:action(/:id))(.:format)'
end

Restaurant/app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :bookingDate, :customerName, :peopleNo, :email, :contactNumber
  EMAIL_REGEX = /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  validates :email, :format => EMAIL_REGEX
  validates :customerName, :presence => true
  validate :booking_date, :people_number
  
  def booking_date
    if !bookingDate.blank? and bookingDate < Date.today
      errors.add(:bookingDate, "Can't be in the past")
    end
  end
  
  def people_number
    if !peopleNo.blank? and peopleNo < 1
      errors.add(:peopleNo, "Provide how many person for reservation")
    end
  end
  
end

Restaurant/app/models/dessert.rb
class Dessert < ActiveRecord::Base
  attr_accessible :description, :name, :price
end

Restaurant/app/models/drink.rb
class Drink < ActiveRecord::Base
  attr_accessible :description, :name, :price
end

Restaurant/app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :dishName, :description, :price
end

Restaurant/app/models/starter.rb
class Starter < ActiveRecord::Base
  attr_accessible :description, :name, :price
end

Restaurant/app/models/subscribe.rb
class Subscribe < ActiveRecord::Base
  EMAIL_REGEX = /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :customerName, :presence => true
  attr_accessible :customerName, :email
end

Restaurant/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Restaurant/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookings }
    end
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @booking = Booking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @booking }
    end
  end

  # GET /bookings/new
  # GET /bookings/new.json
  def new
    @booking = Booking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @booking }
    end
  end

  # GET /bookings/1/edit
  def edit
    @booking = Booking.find(params[:id])
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(params[:booking])

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render json: @booking, status: :created, location: @booking }
      else
        format.html { render action: "new" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookings/1
  # PUT /bookings/1.json
  def update
    @booking = Booking.find(params[:id])

    respond_to do |format|
      if @booking.update_attributes(params[:booking])
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    respond_to do |format|
      format.html {redirect_to :back}
      format.json { head :no_content }
    end
  end
end

Restaurant/app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
  end
end

Restaurant/app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

Restaurant/app/controllers/menu_controller.rb
class MenuController < ApplicationController
  
  def displayMenu
  end
  
  def new
    @menu = Menu.new

    respond_to do |format|
      format.html
      format.json {render json: @menu}
      
    end
  end
    
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to admin_path}
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
    @menu = Menu.find(params[:id])
  end
  
  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to admin_path}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end
  
   def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html {redirect_to admin_path}
      format.json { head :no_content }
    end
  end
  
end

Restaurant/app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController

  def index
    @subscribes = Subscribe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscribes }
    end
  end
  
  def edit
    @subscribe = Subscribe.find(params[:id])
  end
  
  def update
    @subscribe = Subscribe.find(params[:id])

    respond_to do |format|
      if @subscribe.update_attributes(params[:subscribe])
        format.html { redirect_to @subscribe, notice: 'Subscribe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscribe.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @subscribe = Subscribe.find(params[:id])
    @subscribe.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
  
  def show
    @subscribe = Subscribe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscribe }
    end
  end
  
  def new
    @subscribe = Subscribe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscribe }
    end
  end
  
  def create
    @subscribe = Subscribe.new(params[:subscribe])
    
    respond_to do |format|
      if @subscribe.save
          format.html { redirect_to @subscribe, notice: 'Subscription was successfully created.' }
          format.json { render json: @subscribe, status: :created, location: @subscribe }
      else
        format.html { render action: "new" }
        format.json { render json: @subscribe.errors, status: :unprocessable_entity }
      end
    end
  end

end

Restaurant/app/helpers/application_helper.rb
module ApplicationHelper
end

Restaurant/app/helpers/bookings_helper.rb
module BookingsHelper
end

Restaurant/app/helpers/contact_helper.rb
module ContactHelper
end

Restaurant/app/helpers/index_helper.rb
module IndexHelper
end

Restaurant/app/helpers/menu_helper.rb
module MenuHelper
end

Restaurant/app/helpers/subscribes_helper.rb
module SubscribesHelper
end

Restaurant/app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div align="center">
  <div class="f">
    <p>Your Name: <br /><%= f.text_field :customerName %></p>
    <p>Booking Date: <br /><%= f.date_select :bookingDate %></p>
    <p>Number of people: <br /><%= f.number_field :peopleNo %></p>
    <p>Contact Number: <br /><%= f.text_field :contactNumber %></p>
    <p>Email: <br /><%= f.text_field :email %></p>
    <button id="radio">Submit</button>
  </div>
 </div>
<% end %>

Restaurant/app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

Restaurant/app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<table>
  <tr>
    <th>Customername</th>
    <th>Bookingdate</th>
    <th>Peopleno</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bookings.each do |booking| %>
  <tr>
    <td><%= booking.customerName %></td>
    <td><%= booking.bookingDate %></td>
    <td><%= booking.peopleNo %></td>
    <td><%= link_to 'Show', booking %></td>
    <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
    <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Booking', new_booking_path %>

Restaurant/app/views/bookings/new.html.erb
<div class="subs">
	<h3 style="text-align: center">New Booking</h3>
	<p>Fill up the form to make a reservation</p>
</div>
<%= render 'form' %>

Restaurant/app/views/bookings/show.html.erb
<h3 id="notice" style="text-align: center"><%= notice %></h3>


Restaurant/app/views/contact/contact.html.erb
<div class="hero-unit">
  <h1 align="center">Contact</h1>
</div>

<table class="table">
  
   <tbody>
          <tr>
            <td>Phone </td>
            <td>0845019483</td>
          </tr>
          <tr>
            <td>Mail</td>
            <td>restaurant@jdq.ie</td>
          </tr>
          <tr>
            <td>Adress</td>
            <td>6 Merrion Row Dublin 4, Co. Dublin</td>
          </tr>
    </tbody>
</table>

<iframe width="660" height="250" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" 
src="https://maps.google.fr/maps?q=53.338724,-6.25585&amp;num=1&amp;ie=UTF8&amp;t=m&amp;ll=53.338817,-6.255255&amp;
spn=0.01025,0.051413&amp;z=14&amp;output=embed"></iframe><br />
<a href="https://maps.google.fr/maps?q=53.338724,-6.25585&amp;num=1&amp;ie=UTF8&amp;t=m&amp;ll=53.338817,-6.255255&amp;spn=0.01025,0.051413&amp;z=14&amp;source=embed" style="color:#0000FF;text-align:left">Enlarge the map</a>

Restaurant/app/views/index/index.html.erb
<span id="sl_play" class="sl_command">&nbsp;</span>
    <span id="sl_pause" class="sl_command">&nbsp;</span>
    
    <section id="slideshow">
    
        
        <a class="play_commands pause" href="#sl_pause" title="Maintain paused">Pause</a>
        <a class="play_commands play" href="#sl_play" title="Play the animation">Play</a>
        
        <div class="contain">
            <div class="c_slider"></div>
            <div class="slider">
                <figure>
                    <%= image_tag ("slide1.jpg") %>
                    <figcaption>Summer is coming !</figcaption>
                </figure><!--
                --><!--
                --><figure>
                    <%= image_tag ("slide3.jpg") %>
                    <figcaption>Fresh salads !</figcaption>
                </figure><!--
                --><figure>
                    <%= image_tag ("slide4.JPG") %>
                    <figcaption>Enjoy your lunch time</figcaption>
                </figure>
            
            <figure>
                    <%= image_tag ("slide2.jpg") %>
                    <figcaption>Dessert of the day</figcaption>
                </figure></div>
        </div>   

        
    </section>
    
    <p>Le Jardin du Quai is an award winning Michelin star restaurant in Dublin city centre, head chef Ross 
        Lewis focuses on local & seasonal produce to create an array of modern dishes with a combination
         of robust flavours</p>
    <p>Le Jardin du Quai opened in February 1992 with co-proprietors Ross Lewis and Martin Corbett.
        It is located in the Merrion Row in Dublin's city centre.
</p>
<p>A flavour of what is said about Le Jardin Du Quai - Saveur Magazine U.S editor Colman Andrews' favourite Dublin
 restaurant, Tom Doorly - Irish Times "This sestaurant is not just about truly brilliant food.
It's also about the very essence of Irish hospitality".</p>

<button class="btn-success btn-primary btn-large" type="submit"><%= link_to 'Booking', new_booking_path %> <i class="icon-white icon-ok-sign"></i> </button>
<br>
    <h3>Reviews</h3>
<div class="alert span11 alert-info alert-block">

<p>
<strong>Superb Restaurant</strong><br><br>
April 14, 2013<br><br>
<i>
Have lunch here with my son on a regular basis and always find the food delicious and top notch!
It has a lovely friendly and comfy atmosphere and the service is excellent and food reasonably priced. 
Great value for money.Terrific for Special Occaisions. Definitely worth a trip</i></p>
</div>
<div class="alert span11 alert-info alert-block">

<p>
<strong>You'll not be disappointed !</strong><br><br>
April 1, 2013<br><br>
<i>
We went here for a meal last weekend and it was absolutely fantastic, food, staff and ambience were all faultless.
We cannot wait to return for a visit next year, I would highly recommend this restaurant :-)</i></p>
</div>

Restaurant/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant</title>
  <%= stylesheet_link_tag    "application", "scaffolds", :media => "all" %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
<!-- header -->
<div class="row-fluid">
	<div class="span6 offset3">
		<%= image_tag("logo.png", :alt => "logo") %>
		<ul class="nav nav-pills right">
  			<li class="active"><%= link_to 'Home', index_path(@index) %></li>
  			<li class="active"><%= link_to 'Menu', menu_path %></li>
  			<li class="active"><%= link_to 'Booking', new_booking_path %> </li>
  			<li class="active"><%= link_to 'Subscribe', new_subscribe_path %></li>
  			<li class="active"><%= link_to 'Contact', contact_path(@contact) %></li>
		</ul>
	</div>
</div>
<!--  Body -->
<div class="row-fluid "><div class="span6 offset3 page">
<%= yield %>
 </div></div>

<!-- Footer -->
 <div class="row-fluid footer "><div class="span6 offset3">

<div class="row-fluid">
<div class="span4 subfooter">
<ul>
	<li><a href="#">Home</a></li>
	<li><a href="#">Menu</a></li>
	<li><a href="#">Contact</a></li>
</ul>

</div>
<div class="span4 subfooter2">This is the footer 2</div>
<div class="span4 subfooter">
<%= image_tag("facebook_32.png", :alt => "facebook") %>
<%= image_tag("rss_32.png", :alt => "rss feed") %>
<%= image_tag("twitter_32.png", :alt => "twitter") %>
</div>
</div>
 </div></div>
</div>
</body>
</html>

Restaurant/app/views/menu/displayMenu.html.erb
<h1>Menu#displayMenu</h1>

<h2>Starters</h2>

<% start=Starter.all() %>
<table>
	<tr>
		<th> Name  </th>
		<th> Description </th>
		<th> Price </th>
	</tr>


	<tr>
		<% start.each do |d| %>
		<td> <%= d.name %> </td>
		<td> <%= d.description %> </td>
		<td> <%= d.price %> </td>
	</tr>
	<% end %>
</table>

<h2>Main Dishes</h2>

<% dish=Menu.all() %>
<table>
	<tr>
		<th> Name  </th>
		<th> Description </th>
		<th> Price </th>
	</tr>


	<tr>
		<% dish.each do |d| %>
		<td> <%= d.dishName %> </td>
		<td> <%= d.description %> </td>
		<td> <%= d.price %> </td>
	</tr>
	<% end %>
</table>

<h2>Desserts</h2>

<% dess=Dessert.all() %>
<table>
	<tr>
		<th> Name  </th>
		<th> Description </th>
		<th> Price </th>
	</tr>


	<tr>
		<% dess.each do |d| %>
		<td> <%= d.name %> </td>
		<td> <%= d.description %> </td>
		<td> <%= d.price %> </td>
	</tr>
	<% end %>
</table>

<h2>Drinks</h2>

<% drink=Drink.all() %>
<table>
	<tr>
		<th> Name  </th>
		<th> Description </th>
		<th> Price </th>
	</tr>


	<tr>
		<% drink.each do |d| %>
		<td> <%= d.name %> </td>
		<td> <%= d.description %> </td>
		<td> <%= d.price %> </td>
	</tr>
	<% end %>
</table>



<p>Find me in app/views/menu/displayMenu.html.erb</p>

Restaurant/app/views/subscribes/_form.html.erb
<%= form_for(@subscribe) do |f| %>
  <% if @subscribe.errors.any? %>
  <div align="center">
    <div class="errorExplanation">
      <h2><%= pluralize(@subscribe.errors.count, "error") %> , please correct your errors:</h2>

      <ul>
      <% @subscribe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
  <% end %>
  <div align="center">
  	<div class="f">
    	<p>Your Name: <br /><%= f.text_field :customerName %></p>
    	<p>Email Address: <br /><%= f.text_field :email %></p>
    	<button id="radio">Submit</button>
  	</div>
  </div>
<% end %>

Restaurant/app/views/subscribes/edit.html.erb
<h1>Editing subscribe</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscribe %> |
<%= link_to 'Back', subscribes_path %>

Restaurant/app/views/subscribes/index.html.erb
<h1>Listing subscribes</h1>

<table>
  <tr>
    <th>Customername</th>
    <th>Contactno</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscribes.each do |subscribe| %>
  <tr>
    <td><%= subscribe.customerName %></td>
    <td><%= subscribe.contactNo %></td>
    <td><%= subscribe.email %></td>
    <td><%= subscribe.password %></td>
    <td><%= link_to 'Show', subscribe %></td>
    <td><%= link_to 'Edit', edit_subscribe_path(subscribe) %></td>
    <td><%= link_to 'Destroy', subscribe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscribe', new_subscribe_path %>

Restaurant/app/views/subscribes/new.html.erb
<div class="subs">
	<h3 style="text-align: center">10% Off to 3rd level students</h3>
	<p>Just flash your student card on payment<br />Participating universities and colleges can be found below</p>
</div>

<div>
	<canvas id="myCanvas" width="700" height="500"></canvas>
    <script>
      var canvas = document.getElementById('myCanvas');
      var context = canvas.getContext('2d');
      var imageObj = new Image();
      var imageObj2 = new Image();
      var imageObj3 = new Image();

      imageObj.onload = function() 
      {
        context.drawImage(imageObj, 0, 10);
      };
      imageObj.src = 'http://usi.ie/wp-content/uploads/2012/08/TOP_LOGO_USI_FULL.png';
      
      imageObj2.onload = function()
      {
      	context.drawImage(imageObj2, 450, -30);
      };
      imageObj2.src = 'http://campusit.net/wp-content/uploads/2011/07/dit_casestudy_logo.jpg';
      
      imageObj3.onload = function() 
      {
        context.drawImage(imageObj3, 150, 160);
      };
      imageObj3.src = 'http://www.universitiesireland.ie/images/ui-logo.gif';
    </script>
</div>

<div>
	<div class="subs">
		<h4 style="text-align: center">Or you can subscribe on our website to get the latest deal</h4>
		<p>Just provide your name and your email address</p>
	</div>
<%= render 'form' %>
</div>

Restaurant/app/views/subscribes/show.html.erb
<h3 id="notice" style="text-align: center"><%= notice %></h3>